# CONFIG

TASK: "" # Task Name
DATA_TABLE: ""  # Path to save the metadata, a sample file is given in ./dataset/meta_data.csv
LABEL_NAME: "Label"  # Label column name in the metadata file

PATCH:
    IDX2IMG: "./result/tiled_patches/dict_name2imgs.pkl" # Path indicating the place to save the tiled patches.

PRETRAIN:
    MODEL_NAME: 'efficientnet-b0' # patch feature extraction model name
    MODEL_PATH: './checkpoints/Efficientnet/efficientnet-b0-355c32eb.pth' # Path storing the pre-trained model document
    SAVE_DIR: './result/patch_extracted_features' # Path indicating the place to save the extracted patch features
    SAVE_DIR_COMBINED: './result/patch_extracted_features_combined' # Path indicating the place to save the combinded extracted patch features (all path features in a WSI is stored as one data file.)
    TRAIN_FEA_TIMES: 1
#model: MODEL_NAME, NUM_INPUT_CHANNELS, NUM_CLASSES
MODEL:
    MODEL_NAME: 'SETMIL'
    NUM_CLASSES: 2

MODEL_T2T:
    ASPP_FLAG: 1
    ATTN_DROP_RATE: 0.2
    CHANNEL_REDUCE_RATE: 5
    DEPTH: 6
    DROP_RATE: 0.2
    EMBED_DIM: 64
    IRPE: 1
    IRPE_METHOD: "euc"
    IRPE_MODE: "bias"
    IRPE_RPE_ON: "q"
    IRPE_SHARE_HEAD: False
    NUM_CLASSES: 2
    NUM_HEADS: 16
    NUM_INPUT_CHANNELS: 1280
    TOKEN_DIM: 128
    TOKEN_T_ATTN_DROP_RATE: 0.2
    TOKEN_T_DROP_RATE: 0.2
    TOKEN_T_IRPE: 0
    TOKEN_T_IRPE_METHOD: "euc"
    TOKEN_T_IRPE_MODE: "bias"
    TOKEN_T_IRPE_RPE_ON: "q"
    TOKEN_T_IRPE_SHARE_HEAD: False

DATASET:
    DATASET_NAME: 'cnn'
    DATASET_SEED: 1
    DATASET_SCALE: 'x20'
    FEATURE_MAP_SIZE: 48

# train: EPOCHS, BATCH_SIZE, LR
TRAIN:
    LOSS_NAME: 'be'
    EPOCHS: 100 
    START_EPOCH: 0
    BATCH_SIZE: 4 
    NUM_WORKERS: 10
    LR: 2e-4
    LR_DROP: 40
    LR_BACKBONE: 2e-5
    LR_LINEAR_PROJ_MULT: 0.1
    WEIGHT_DECAY: 1e-4
    CLIP_MAX_NORM: 0.01
    OPTIM_NAME: 'adamw'
    EVAL: False
    OUTPUT_DIR: './result' # Path to store the obtained model and results
    SEED: 4
    CACHE_MODE: False
    CLS_LOSS_COEF: 2 # for transformer below
    BOX_LOSS_COEF: 5
    GIOU_LOSS_COEF: 2
    MASK_LOSS_COEF: 1
    DICE_LOSS_COEF: 1
    FOCAL_ALPHA: 0.25
    MODEL_PATH:
        LUAD_GM: "./checkpoints/SETMIL/LUAD_GM.pth"
        EC_LNM: "./checkpoints/SETMIL/EC_LNM_1.pth"